# Generated by Django 3.2.16 on 2023-03-30 07:27

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(verbose_name="Сообщение пользователя"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("handling", "В обработке"),
                            ("answered", "Ответ дан"),
                        ],
                        default="received",
                        max_length=8,
                        verbose_name="статус обработки",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение пользователя",
                "verbose_name_plural": "сообщения пользователей",
            },
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        verbose_name="почта пользователя, оставившего сообщение",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=feedback.models.feedback_upload_path
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedback",
            name="personal_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_information",
                to="feedback.personalinformation",
            ),
        ),
    ]
