# Generated by Django 3.2.16 on 2023-03-24 20:10

import django.db.migrations
import django.db.models

import feedback.models


class Migration(django.db.migrations.Migration):
    replaces = [
        ("feedback", "0001_initial"),
        ("feedback", "0002_auto_20230313_1417"),
        ("feedback", "0003_auto_20230313_2011"),
        ("feedback", "0004_feedback_personal_information"),
        ("feedback", "0005_auto_20230318_2038"),
    ]

    dependencies = []

    operations = [
        django.db.migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    django.db.models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    django.db.models.EmailField(
                        max_length=254,
                        verbose_name=(
                            "Почта пользователя," " оставившего сообщение"
                        ),
                    ),
                ),
            ],
        ),
        django.db.migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    django.db.models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django.db.models.TextField(
                        verbose_name="Сообщение пользователя"
                    ),
                ),
                (
                    "created_on",
                    django.db.models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "status",
                    django.db.models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("handling", "В обработке"),
                            ("answered", "Ответ дан"),
                        ],
                        default="received",
                        max_length=8,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "personal_information",
                    django.db.models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_information",
                        to="feedback.personalinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение пользователя",
                "verbose_name_plural": "сообщения пользователей",
            },
        ),
        django.db.migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    django.db.models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    django.db.models.FileField(
                        upload_to=feedback.models.feedback_upload_path
                    ),
                ),
                (
                    "feedback",
                    django.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                    ),
                ),
            ],
        ),
    ]
