# Generated by Django 3.2.16 on 2023-03-13 11:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Получено"),
                    ("handling", "В обработке"),
                    ("answered", "Ответ дан"),
                ],
                default="received",
                max_length=8,
                verbose_name="Статус обработки",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время создания"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(
                max_length=254,
                verbose_name="Почта пользователя, оставившего сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(verbose_name="Сообщение пользователя"),
        ),
    ]
