# Generated by Django 3.2.16 on 2023-03-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_auto_20230313_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="personal_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.personalinformation",
            ),
            preserve_default=False,
        ),
    ]
