# Generated by Django 3.2.16 on 2023-03-18 17:38

from django.db import migrations
from django.db import models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_feedback_personal_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="personal_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_information",
                to="feedback.personalinformation",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                upload_to=feedback.models.feedback_upload_path
            ),
        ),
    ]
