# Generated by Django 3.2.16 on 2023-03-18 17:38

import django.conf
import django.db.migrations
import django.db.models


class Migration(django.db.migrations.Migration):
    initial = True

    dependencies = [
        django.db.migrations.swappable_dependency(
            django.conf.settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        django.db.migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    django.db.models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birthday",
                    django.db.models.DateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
                (
                    "image",
                    django.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="item/main/%Y/%m/%d",
                        verbose_name="аватарка",
                    ),
                ),
                (
                    "coffee_count",
                    django.db.models.PositiveIntegerField(
                        default=0, verbose_name="сколько раз сварил кофе"
                    ),
                ),
                (
                    "user",
                    django.db.models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное поле",
                "verbose_name_plural": "Дополнительные поля",
            },
        ),
    ]
