# Generated by Django 3.2.16 on 2023-03-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "catalog",
            "0002_auto_20230226_1500_squashed_0010_auto_20230307_0032",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Very bad"),
                            (2, "Bad"),
                            (3, "Neutral"),
                            (4, "Good"),
                            (5, "Very good"),
                        ],
                        help_text="Целое число от 1 до 5",
                        verbose_name="оценка",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв/оценка товара",
            },
        ),
    ]
