# Generated by Django 3.2.16 on 2023-02-19 11:27

import catalog.models

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "text",
                    models.TextField(
                        validators=[catalog.models.exist_adverbs_validator]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_published", models.BooleanField(default=True)),
                ("slug", models.SlugField(max_length=200)),
            ],
        ),
    ]
