# Generated by Django 3.2.16 on 2023-03-30 07:27

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название. Максимум 150 символов",
                        max_length=150,
                        verbose_name="название",
                    ),
                ),
                (
                    "name_normalized",
                    models.CharField(
                        editable=False, max_length=200, unique=True
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Уберите галочку, если хотите скрыть запись",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Укажите слаг, который будет отображаться в ссылке",
                        max_length=200,
                        verbose_name="слаг",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=150,
                        help_text="Укажите массу",
                        verbose_name="масса",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название. Максимум 150 символов",
                        max_length=150,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Уберите галочку, если хотите скрыть запись",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text="Придумайте описание. Текст должен включать слова превосходно или роскошно",
                        validators=[
                            catalog.validators.ValidateMustContain(
                                "превосходно", "роскошно"
                            )
                        ],
                        verbose_name="описание",
                    ),
                ),
                (
                    "is_on_main",
                    models.BooleanField(
                        default=False,
                        help_text="Поставьте галочку, если хотите отобразить товар на главной странице",
                        verbose_name="добавить на главную страницу",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateField(
                        auto_now=True, verbose_name="дата последнего изменения"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию или добавьте новую",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.CreateModel(
            name="ItemImageMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_main",
                    models.ImageField(upload_to="item/main/%Y/%m/%d"),
                ),
            ],
            options={
                "verbose_name": "фото главное",
                "verbose_name_plural": "фото главные",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название. Максимум 150 символов",
                        max_length=150,
                        verbose_name="название",
                    ),
                ),
                (
                    "name_normalized",
                    models.CharField(
                        editable=False, max_length=200, unique=True
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Уберите галочку, если хотите скрыть запись",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Укажите слаг, который будет отображаться в ссылке",
                        max_length=200,
                        verbose_name="слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="ItemImageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_gallery",
                    models.ImageField(upload_to="item/gallery/%Y/%m/%d"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото галерея",
                "verbose_name_plural": "фото галерея",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.itemimagemain",
                verbose_name="главное фото",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите тег или создайте новый",
                to="catalog.Tag",
                verbose_name="теги",
            ),
        ),
    ]
