# Generated by Django 3.2.16 on 2023-03-29 11:30

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial_squashed_0005_alter_item_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimagegallery",
            options={
                "verbose_name": "фото галерея",
                "verbose_name_plural": "фото галерея",
            },
        ),
        migrations.AlterModelOptions(
            name="itemimagemain",
            options={
                "verbose_name": "фото главное",
                "verbose_name_plural": "фото главные",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="date_created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="date_updated",
            field=models.DateField(
                auto_now=True, verbose_name="дата последнего изменения"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Поставьте галочку, если хотите отобразить товар на главной странице",
                verbose_name="добавить на главную страницу",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Придумайте описание. Текст должен включать слова превосходно или роскошно",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="itemimagegallery",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="catalog.item",
            ),
        ),
    ]
