# Generated by Django 3.2.16 on 2023-03-07 09:28

import catalog.validators
from django.db import migrations
from django.db import models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):
    replaces = [
        ("catalog", "0002_auto_20230226_1500"),
        ("catalog", "0003_alter_item_text"),
        ("catalog", "0004_auto_20230305_1217"),
        ("catalog", "0005_alter_itemimagegallery_item"),
        ("catalog", "0006_auto_20230306_2245"),
        ("catalog", "0007_auto_20230307_0028"),
        ("catalog", "0008_auto_20230307_0029"),
        ("catalog", "0009_auto_20230307_0031"),
        ("catalog", "0010_auto_20230307_0032"),
    ]

    dependencies = [
        ("catalog", "0001_initial_squashed_0005_alter_item_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimagegallery",
            options={
                "verbose_name": "фото галерея",
                "verbose_name_plural": "фото галерея",
            },
        ),
        migrations.AlterModelOptions(
            name="itemimagemain",
            options={
                "verbose_name": "фото главное",
                "verbose_name_plural": "фото главные",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Придумайте описание. Текст "
                "должен включать слова превосходно "
                "/ роскошно",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Поставьте галочку, если хотите "
                "отобразить товар на главной странице",
                verbose_name="добавить на главную страницу",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Придумайте описание. Текст должен "
                "включать слова превосходно или роскошно",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="itemimagegallery",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="catalog.item",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="date_created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="date_updated",
            field=models.DateField(
                auto_now=True, verbose_name="дата последнего " "изменения"
            ),
        ),
    ]
