# Generated by Django 3.2.16 on 2023-02-26 12:02

import catalog.validators

from django.db import migrations

import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_auto_20230226_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Придумайте описание. "
                "Текст должен включать слова "
                "превосходно / роскошно",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
    ]
