# Generated by Django 3.2.16 on 2023-03-05 08:17

import catalog.validators
from django.db import migrations
from django.db import models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Поставьте галочку, если хотите "
                "отобразить товар на главной странице",
                verbose_name="добавить на главную страницу",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Придумайте описание. Текст должен "
                "включать слова превосходно "
                "или роскошно",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
    ]
