# Generated by Django 3.2.16 on 2023-03-05 17:58

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_auto_20230305_1217"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimagegallery",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="catalog.item",
            ),
        ),
    ]
