# Generated by Django 3.2.16 on 2023-03-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20230306_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='дата последнего изменения'),
        ),
    ]
