# Generated by Django 3.2.16 on 2023-03-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20230307_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_updated',
        ),
    ]
